/**
 * TenantSatisfactionPage — 22 Tenant Satisfaction Measures.
 *
 * The Regulator of Social Housing requires English social landlords to
 * report 22 measures annually. This page renders the latest year's
 * values with regulator codes, benchmark comparison, year-on-year trend
 * and a one-click CSV export in the regulator's expected format.
 *
 * Backend: GET /api/tsm/measures, /api/tsm/regulator-return.csv
 */
import { useEffect, useMemo, useState } from 'react'
import type { CSSProperties } from 'react'
import axios from 'axios'
import DataSourceBanner from '../components/DataSourceBanner'

interface Measure {
  code: string
  name: string
  category: string
  unit: string
  higher_is_better: boolean
  value: number
  benchmark: number | null
  band: 'green' | 'amber' | 'red'
  year: number
  responses: number
  trend_vs_prior_year: number | null
}

interface MeasureBundle {
  year: number | null
  measures: Measure[]
}

const PAGE: CSSProperties = {
  padding: '24px 32px',
  maxWidth: 1400,
  margin: '0 auto',
  color: '#111827',
  fontFamily: 'system-ui, -apple-system, sans-serif',
}

const BAND_BG: Record<Measure['band'], string> = {
  green: '#ECFDF5',
  amber: '#FFFBEB',
  red:   '#FEF2F2',
}
const BAND_BORDER: Record<Measure['band'], string> = {
  green: '#A7F3D0',
  amber: '#FCD34D',
  red:   '#FCA5A5',
}
const BAND_TEXT: Record<Measure['band'], string> = {
  green: '#065F46',
  amber: '#92400E',
  red:   '#991B1B',
}

const CATEGORY_ORDER = [
  'Tenant Perception',
  'Repairs',
  'Building Safety',
  'Decent Homes',
  'Neighbourhood',
  'Anti-social Behaviour',
]

export default function TenantSatisfactionPage() {
  const [bundle, setBundle] = useState<MeasureBundle | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    axios.get<MeasureBundle>('/api/tsm/measures')
      .then(r => { if (!cancelled) setBundle(r.data) })
      .catch(e => { if (!cancelled) setError((e as Error).message) })
      .finally(() => { if (!cancelled) setLoading(false) })
    return () => { cancelled = true }
  }, [])

  // Group by category for display
  const grouped = useMemo(() => {
    const out: Record<string, Measure[]> = {}
    for (const m of bundle?.measures ?? []) {
      out[m.category] ||= []
      out[m.category].push(m)
    }
    return out
  }, [bundle])

  const overall = bundle?.measures.find(m => m.code === 'TP01')
  const greenCount = bundle?.measures.filter(m => m.band === 'green').length ?? 0
  const redCount   = bundle?.measures.filter(m => m.band === 'red').length ?? 0

  if (loading) return <div style={PAGE}>Loading TSMs…</div>
  if (error) return <div style={{ ...PAGE, color: '#991B1B' }}>Failed to load: {error}</div>

  return (
    <div style={PAGE}>
      <header style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 24 }}>
        <div>
          <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 4 }}>Tenant Satisfaction Measures</h1>
          <p style={{ fontSize: 14, color: '#6B7280' }}>
            All 22 measures the Regulator of Social Housing requires annually
            {bundle?.year ? <> · survey year <strong>{bundle.year}</strong></> : null}
          </p>
        </div>
        <a
          href="/api/tsm/regulator-return.csv"
          style={{
            padding: '10px 20px',
            border: '1px solid #1B4F72',
            backgroundColor: '#1B4F72',
            color: 'white',
            borderRadius: 8,
            fontSize: 14,
            fontWeight: 600,
            textDecoration: 'none',
          }}
        >
          Download regulator return (CSV)
        </a>
      </header>

      <DataSourceBanner
        pageKey="tsm"
        mode="synthetic"
        summary="The TSM values on this page are fabricated. They are not from any real survey. They were generated by the Phase 3 seed migration so the dashboard has something to render."
        rules={[
          "Each measure has a baseline value and a spread. For example TP01 (overall satisfaction) is sampled from 75% ± 5; BP01 (gas safety) from 96% ± 1.5; CH01 (Decent Homes) from 94% ± 2; CH02 (failing Decent Homes) from 12% ± 2.5. The values you see are baseline ± random variance.",
          "Two years of synthetic data are generated (current and prior) so trend arrows have something to compute against.",
          "Response counts are random integers in [500, 2000]. Ward and Local Authority breakdowns are not seeded yet so portfolio-level numbers are aggregated nationally.",
          "Benchmarks (the small grey numbers next to each value) ARE real — they are industry medians from Housemark and the Regulator of Social Housing 2024 publications.",
        ]}
        productionSource="Two sources: (1) the Tenant Perception measures (TP01–TP12) come from a regulator-compliant survey run by a provider like BMG Research, Acuity, or IFF — typically delivered as an annual CSV or via API; (2) the management measures (RP01, RP02, BP01, CH01–02, NM01, AS01) are computed from your own operational data — repairs records, gas safety register, Decent Homes assessments, ASB case logs."
      >
        <strong>What is real:</strong> the 19 measure definitions and codes, the regulator's
        unit conventions (% for perception, per 1,000 homes for ASB), the higher-is-better /
        lower-is-better polarity, and the CSV download format. Pipe in a real survey feed and
        the dashboard works unchanged.
      </DataSourceBanner>

      <section style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: 16,
        marginBottom: 32,
      }}>
        <KpiCard title="Overall satisfaction (TP01)" value={overall ? `${overall.value}%` : '—'} subtitle={overall ? `Benchmark ${overall.benchmark}%` : ''} />
        <KpiCard title="Measures meeting benchmark" value={`${greenCount}/22`} subtitle="Green-band measures" />
        <KpiCard title="Measures below benchmark" value={`${redCount}/22`} subtitle="Need attention" />
      </section>

      {CATEGORY_ORDER.map(cat => {
        const measures = grouped[cat]
        if (!measures || measures.length === 0) return null
        return (
          <section key={cat} style={{ marginBottom: 32 }}>
            <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 12 }}>{cat}</h2>
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
              gap: 12,
            }}>
              {measures.map(m => <MeasureCard key={m.code} m={m} />)}
            </div>
          </section>
        )
      })}
    </div>
  )
}

function KpiCard({ title, value, subtitle }: { title: string; value: string; subtitle?: string }) {
  return (
    <div style={{
      backgroundColor: 'white',
      border: '1px solid #E5E7EB',
      borderRadius: 12,
      padding: '20px 24px',
    }}>
      <div style={{ fontSize: 12, color: '#6B7280', textTransform: 'uppercase', fontWeight: 600 }}>{title}</div>
      <div style={{ fontSize: 32, fontWeight: 700, marginTop: 4 }}>{value}</div>
      {subtitle && <div style={{ fontSize: 12, color: '#9CA3AF', marginTop: 4 }}>{subtitle}</div>}
    </div>
  )
}

function MeasureCard({ m }: { m: Measure }) {
  const trendArrow =
    m.trend_vs_prior_year == null ? '' :
    m.trend_vs_prior_year > 0 ? (m.higher_is_better ? '▲' : '▼') :
    m.trend_vs_prior_year < 0 ? (m.higher_is_better ? '▼' : '▲') : '·'

  const trendColor =
    m.trend_vs_prior_year == null ? '#9CA3AF' :
    (m.higher_is_better ? m.trend_vs_prior_year >= 0 : m.trend_vs_prior_year <= 0)
      ? '#065F46' : '#991B1B'

  const valueDisplay = m.unit === '%' ? `${m.value}%` : `${m.value} ${m.unit}`

  return (
    <div style={{
      backgroundColor: BAND_BG[m.band],
      border: `1px solid ${BAND_BORDER[m.band]}`,
      borderRadius: 10,
      padding: 16,
    }}>
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 8 }}>
        <span style={{
          fontSize: 11,
          fontWeight: 700,
          color: BAND_TEXT[m.band],
          backgroundColor: 'white',
          padding: '2px 8px',
          borderRadius: 4,
          letterSpacing: 0.5,
        }}>
          {m.code}
        </span>
        {m.trend_vs_prior_year != null && (
          <span style={{ fontSize: 12, color: trendColor, fontWeight: 600 }}>
            {trendArrow} {Math.abs(m.trend_vs_prior_year)} pt
          </span>
        )}
      </div>
      <div style={{ fontSize: 14, fontWeight: 600, color: '#111827', marginBottom: 8, minHeight: 40 }}>
        {m.name}
      </div>
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between' }}>
        <div style={{ fontSize: 24, fontWeight: 700, color: BAND_TEXT[m.band] }}>{valueDisplay}</div>
        {m.benchmark != null && (
          <div style={{ fontSize: 12, color: '#6B7280' }}>
            benchmark {m.benchmark}{m.unit === '%' ? '%' : ''}
          </div>
        )}
      </div>
      <div style={{ fontSize: 11, color: '#6B7280', marginTop: 8 }}>
        based on {m.responses.toLocaleString()} responses
      </div>
    </div>
  )
}
